#!/bin/sh
set -euo pipefail

# 환경변수에서 사용자와 비밀번호를 읽어 생성합니다. 없으면 기본값 사용(로컬 개발 편의)
BOSS_DB_USER=${BOSS_DB_USER:-boss_user}
BOSS_DB_PASSWORD=${BOSS_DB_PASSWORD:-boss_password}
CHAR_DB_USER=${CHAR_DB_USER:-character_user}
CHAR_DB_PASSWORD=${CHAR_DB_PASSWORD:-character_password}
SETTLE_DB_USER=${SETTLE_DB_USER:-settlement_user}
SETTLE_DB_PASSWORD=${SETTLE_DB_PASSWORD:-settlement_password}
HISTORY_DB_USER=${HISTORY_DB_USER:-history_user}
HISTORY_DB_PASSWORD=${HISTORY_DB_PASSWORD:-history_password}
ADMIN_DB_USER=${ADMIN_DB_USER:-admin_user}
ADMIN_DB_PASSWORD=${ADMIN_DB_PASSWORD:-admin_password}

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${BOSS_DB_USER}'@'%' IDENTIFIED BY '${BOSS_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${CHAR_DB_USER}'@'%' IDENTIFIED BY '${CHAR_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${SETTLE_DB_USER}'@'%' IDENTIFIED BY '${SETTLE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${HISTORY_DB_USER}'@'%' IDENTIFIED BY '${HISTORY_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${ADMIN_DB_USER}'@'%' IDENTIFIED BY '${ADMIN_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON happy_maple_day_boss.* TO '${BOSS_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON happy_maple_day_character.* TO '${CHAR_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON happy_maple_day_settlement.* TO '${SETTLE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON happy_maple_day_history.* TO '${HISTORY_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON happy_maple_day_admin.* TO '${ADMIN_DB_USER}'@'%';

FLUSH PRIVILEGES;
SQL


